apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-smartfreight
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
  - repoURL: https://charts.loft.sh
    targetRevision: "0.14.1"
    chart: vcluster
    helm:
      values: |
        enableHA: true
        replicas: 2
        vcluster:
          env:
          - name: K3S_DATASTORE_ENDPOINT
            value: postgres://vcsmartfreight:vcsmartfreight@ExACTa@puc-rio.eu.org:5432/vc_smartfreight?sslmode=disable
        coredns:
          replicas: 2
        storage:
          persistence: false
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        sync:
          nodes:
            enabled: true
            nodeSelector: "vcluster=exacta"
          ingresses:
            enabled: true
          hoststorageclasses:
            enabled: true
        syncer:
          extraArgs:
          - --name=vcluster-smartfreight
          - --tls-san=smartfrete.puc-rio.eu.org
        mapServices:
          fromVirtual:
          - from: smartfreight/smartfreight-authserver-service
            to: smartfreight-authserver-service
          - from: smartfreight/smartfreight-calculator-service
            to: smartfreight-calculator-service
          - from: smartfreight/smartfreight-historic-service
            to: smartfreight-historic-service
          - from: smartfreight/smartfreight-railway-service
            to: smartfreight-railway-service
          - from: smartfreight/smartfreight-duct-service
            to: smartfreight-duct-service
          - from: smartfreight/smartfreight-react-service
            to: smartfreight-react-service
#        init:
#          helm:
#          - chart:
#              name: cert-manager
#              repo: https://charts.jetstack.io
#              version: v1.10.1
#            values: |-
#              installCRDs: true
#            release:
#              name: cert-manager
#              namespace: cert-manager
#          - chart:
#              name: kong
#              repo: https://charts.konghq.com
#            # optional field
#            values: |-
#              proxy:
#                type: NodePort
#                http:
#                  nodePort: 30081
#                tls:
#                  nodePort: 30444
#            release:
#              name: kong
#              namespace: kong
#          manifests: |-
#            apiVersion: cert-manager.io/v1
#            kind: ClusterIssuer
#            metadata:
#              name: letsencrypt-prod
#              namespace: cert-manager
#            spec:
#              acme:
#                email: luvres@hotmail.com #please change this
#                privateKeySecretRef:
#                  name: letsencrypt-prod
#                server: https://acme-v02.api.letsencrypt.org/directory
#                solvers:
#                - http01:
#                    ingress:
#                      class: kong
  - repoURL: https://github.com/luvres/platform.git
    path: vcluster/ingress/smartfreight
    targetRevision: HEAD
    
  destination:
    namespace: vcluster-smartfreight
    name: puc-rio
#    server: https://puc-rio.eu.org:6443
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
