apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-exacta
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
#    repoURL: https://github.com/luvres/vcluster.git
#    path: vcluster-exacta
#    targetRevision: HEAD
    repoURL: https://charts.loft.sh
    targetRevision: "0.13.0"
    chart: vcluster
    helm:
#      valueFiles:
#      - values.yaml
      values: |
        enableHA: true
        replicas: 2
        vcluster:
          env:
          - name: K3S_DATASTORE_ENDPOINT
            value: postgres://vcexacta:vcexacta@ExACTa@puc-rio.eu.org:5432/vc_exacta?sslmode=disable
        coredns:
          replicas: 2
        storage:
          persistence: false
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        sync:
          nodes:
            enabled: true
            nodeSelector: "vcluster=exacta"
          ingresses:
            enabled: true
        syncer:
          extraArgs:
          - --name=vcluster-exacta
          - --tls-san=exacta.puc-rio.eu.org
        init:
          helm:
          # public chart
          - chart:
              name: cert-manager
              repo: https://charts.jetstack.io
              version: v1.10.1
            values: |-
              installCRDs: true
            release:
              name: cert-manager
              namespace: cert-manager
          - chart:
              name: kong
              repo: https://charts.konghq.com
            # optional field
            values: |-
              ingressController:
                installCRDs: false
              proxy:
                type: NodePort
                http:
                  nodePort: 30081
                tls:
                  nodePort: 30444
            release:
              name: kong
              namespace: kong
#          manifests: |-
#            apiVersion: cert-manager.io/v1
#            kind: ClusterIssuer
#            metadata:
#              name: letsencrypt-prod
#              namespace: cert-manager
#            spec:
#              acme:
#                email: luvres@hotmail.com #please change this
#                privateKeySecretRef:
#                  name: letsencrypt-prod
#                server: https://acme-v02.api.letsencrypt.org/directory
#                solvers:
#                - http01:
#                    ingress:
#                      class: kong

  destination:
    namespace: vcluster-exacta
    name: default
#    server: https://puc-rio.eu.org:6443
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: vcluster-exacta-ingress
#  namespace: argocd
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/luvres/vcluster.git
#    path: vcluster-exacta
#    targetRevision: HEAD
#  destination:
#    namespace: vcluster-exacta
#    name: default
##    server: https://puc-rio.eu.org:6443
#  syncPolicy:
#    syncOptions:
#    - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
