apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vclusters
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: vcluster-exacta
    repoURL: https://github.com/luvres/vcluster.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: vcluster-exacta
    name: default
#    server: https://puc-rio.eu.org:6443
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
