apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visstorymaker
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: visstorymaker
  sources:
  - repoURL: https://exactapucrio@dev.azure.com/exactapucrio/Petrobras%20-%20Smart%20Frete/_git/gitops
    path: Visstorymaker-back
    targetRevision: HEAD
  destination:
    namespace: visstorymaker
    name: visstorymaker
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
