apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vcluster-ingress-exacta
  namespace: vcluster-exacta
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`exacta.puc-rio.eu.org`)
    services:
    - name: vcluster-exacta
      port: 443
  tls:
    passthrough: true
---
