apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vcluster-ingress-smartfreight
  namespace: vcluster-smartfreight
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`smartfrete.puc-rio.eu.org`)
    services:
    - name: vcluster-smartfreight
      port: 443
  tls:
    passthrough: true
